[Writable]
LogLevel = "INFO"

[Service]
Port = 59993
StartupMsg = "device snmp started"

[MessageBus]
  [MessageBus.Optional]
  # Default MQTT & NATS Specific options that need to be here to enable environment variable overrides of them
  ClientId = "device-snmp"
